"""Remove currency_preference from users table

Revision ID: 9afeff7530ac
Revises: a124808cbe39
Create Date: 2026-01-29 00:57:22.856634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9afeff7530ac'
down_revision: Union[str, None] = 'a124808cbe39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Drop the currency_preference column from users if it exists
    col_check = conn.execute(sa.text(
        "SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' "
        "AND COLUMN_NAME = 'currency_preference'"
    )).fetchone()
    if col_check:
        op.drop_column('users', 'currency_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add currency_preference column if downgrading
    op.add_column('users', sa.Column('currency_preference', mysql.VARCHAR(length=3), nullable=True))
    # ### end Alembic commands ###
