"""Remove currency_preference from users table

Revision ID: 9afeff7530ac
Revises: a124808cbe39
Create Date: 2026-01-29 00:57:22.856634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9afeff7530ac'
down_revision: Union[str, None] = 'a124808cbe39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_action', table_name='audit_logs')
    op.drop_index('idx_audit_user_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_column('users', 'currency_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency_preference', mysql.VARCHAR(length=3), nullable=False))
    op.create_table('audit_logs',
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('tenant_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('action', mysql.ENUM('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'LOGIN_THROTTLED', 'LOGIN_EXCESSIVE_FAILURES', 'TOKEN_REFRESH', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_ROLE_CHANGED', 'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'TENANT_CREATED', 'TENANT_UPDATED', 'TENANT_DELETED', 'INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_DELETED', 'INVOICE_STATUS_CHANGED', 'DATA_EXPORTED', 'INVOICE_PDF_GENERATED'), nullable=False),
    sa.Column('resource_type', mysql.ENUM('USER', 'TENANT', 'INVOICE', 'INVOICE_ITEM', 'AUTH', 'EXPORT'), nullable=False),
    sa.Column('resource_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('changes', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='audit_logs_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_resource_id', 'audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=True)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index('idx_audit_tenant_action', 'audit_logs', ['tenant_id', 'action'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
